package com.emu.tqqserver.db;

import com.zaxxer.hikari.HikariConfig;
import com.zaxxer.hikari.HikariDataSource;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import java.sql.*;

/**
 * SQLite database manager using HikariCP connection pooling.
 *
 * <p>Schema mirrors the game's player data model inferred from:
 * <ul>
 *   <li>Assets.Scripts.Build.BuildInfomation/ApiInfomation (class name suggests API data structure)</li>
 *   <li>SerializedTypes.xml - exposed serialized class names</li>
 *   <li>Namespace: Assets.Scripts.Application.* (Unity scene objects)</li>
 * </ul>
 */
public class DatabaseManager {

    private static final Logger log = LoggerFactory.getLogger(DatabaseManager.class);
    private static final DatabaseManager INSTANCE = new DatabaseManager();

    private HikariDataSource dataSource;

    private DatabaseManager() {}

    public static DatabaseManager getInstance() {
        return INSTANCE;
    }

    public void initialize(String dbPath) {
        HikariConfig config = new HikariConfig();
        com.emu.tqqserver.server.ServerConfig srvConfig = com.emu.tqqserver.game.GameContext.getInstance().getConfig();
        if ("mysql".equalsIgnoreCase(srvConfig.getDbType())) {
            config.setJdbcUrl("jdbc:mariadb://" + srvConfig.getDbHost() + ":" + srvConfig.getDbPort() + "/" + srvConfig.getDbName() + "?useUnicode=true&characterEncoding=utf8&createDatabaseIfNotExist=true");
            config.setUsername(srvConfig.getDbUser());
            config.setPassword(srvConfig.getDbPass());
            config.setDriverClassName("org.mariadb.jdbc.Driver");
            config.setMaximumPoolSize(10);
            log.info("Database initialized with MySQL/MariaDB: {}", config.getJdbcUrl());
        } else {
            config.setJdbcUrl("jdbc:sqlite:" + dbPath);
            config.setDriverClassName("org.sqlite.JDBC");
            config.setMaximumPoolSize(4); // SQLite is single-writer
            config.setConnectionInitSql("PRAGMA journal_mode=WAL; PRAGMA synchronous=NORMAL; PRAGMA foreign_keys=ON; PRAGMA busy_timeout=5000;");
            config.addDataSourceProperty("journal_mode", "WAL");
            config.addDataSourceProperty("synchronous", "NORMAL");
            config.addDataSourceProperty("foreign_keys", "ON");
            log.info("Database initialized with SQLite: {}", dbPath);
        }
        
        config.setConnectionTimeout(30000);

        dataSource = new HikariDataSource(config);
        createSchema();
    }

    public String rewriteSql(String sql) {
        if (!"mysql".equalsIgnoreCase(com.emu.tqqserver.game.GameContext.getInstance().getConfig().getDbType())) {
            return sql;
        }
        String res = sql;
        res = res.replaceAll("(?i)\\bAUTOINCREMENT\\b", "AUTO_INCREMENT");
        res = res.replaceAll("(?i)\\bINSERT OR IGNORE INTO\\b", "INSERT IGNORE INTO");
        res = res.replaceAll("(?i)\\bINSERT OR REPLACE INTO\\b", "REPLACE INTO");
        res = res.replaceAll("(?i)\\bON CONFLICT\\s*\\([^)]+\\)\\s*DO UPDATE SET\\b", "ON DUPLICATE KEY UPDATE");
        res = res.replaceAll("(?i)\\bEXCLUDED\\.([a-zA-Z0-9_]+)", "VALUES($1)");
        res = res.replaceAll("(?i)strftime\\('%s','now'\\)", "UNIX_TIMESTAMP()");
        res = res.replaceAll("(?i)\\bMAX\\(", "GREATEST(");
        return res;
    }

    public PreparedStatement prepareStatement(Connection conn, String sql) throws SQLException {
        return conn.prepareStatement(rewriteSql(sql));
    }

    public PreparedStatement prepareStatement(Connection conn, String sql, int autoGeneratedKeys) throws SQLException {
        return conn.prepareStatement(rewriteSql(sql), autoGeneratedKeys);
    }

    public Connection getConnection() throws SQLException {
        return dataSource.getConnection();
    }

    public void close() {
        if (dataSource != null && !dataSource.isClosed()) {
            dataSource.close();
        }
    }

    // -----------------------------------------------------------------------
    // Schema DDL
    // -----------------------------------------------------------------------

    private void executeSql(Statement stmt, String sql) throws SQLException {
        stmt.execute(rewriteSql(sql));
    }

    private void createSchema() {
        try (Connection conn = getConnection(); Statement stmt = conn.createStatement()) {
            executeSql(stmt, SQL_CREATE_USERS);
            // Ensure auto-increment for users table starts at 10000 (so first inserted user is 10001)
            executeSql(stmt, "INSERT OR IGNORE INTO users (user_id, platform_type, platform_id, device_id) VALUES (10000, 'dummy', 'dummy', 'dummy')");
            executeSql(stmt, "DELETE FROM users WHERE user_id = 10000");

            executeSql(stmt, SQL_CREATE_USER_ITEMS);
            executeSql(stmt, SQL_CREATE_USER_CARDS);
            executeSql(stmt, SQL_CREATE_USER_CHAPTERS);
            executeSql(stmt, SQL_CREATE_USER_CHAPTER_EXPIRES);
            executeSql(stmt, SQL_CREATE_USER_UNITS);
            executeSql(stmt, SQL_CREATE_USER_MEMBERS);
            executeSql(stmt, SQL_CREATE_USER_STAGES);
            executeSql(stmt, SQL_CREATE_USER_STORIES);
            executeSql(stmt, SQL_CREATE_USER_STAMINA);
            executeSql(stmt, SQL_CREATE_GACHA_LOG);
            executeSql(stmt, SQL_CREATE_USER_PRESENTS);
            executeSql(stmt, SQL_CREATE_USER_COLLECTIONS);
            executeSql(stmt, SQL_CREATE_USER_COLLECTION_PAGES);
            executeSql(stmt, SQL_CREATE_USER_COLLECTION_ELEMENTS);

            // Create many-to-many lookup tables
            executeSql(stmt, SQL_CREATE_USER_COOKING);
            executeSql(stmt, SQL_CREATE_USER_HOME_ACTORS);
            executeSql(stmt, SQL_CREATE_USER_FRIENDS);
            executeSql(stmt, SQL_CREATE_USER_BLOCKS);
            executeSql(stmt, SQL_CREATE_USER_GACHA_HISTORY);
            try {
                executeSql(stmt, "ALTER TABLE user_gacha_history ADD COLUMN pending_choice_cnt INTEGER NOT NULL DEFAULT 0");
            } catch (SQLException ignored) {}

            // Migration to add profile options to users if they don't exist
            try { executeSql(stmt, "ALTER TABLE users ADD COLUMN profile_background_id INTEGER NOT NULL DEFAULT 0"); } catch (SQLException ignored) {}
            try { executeSql(stmt, "ALTER TABLE users ADD COLUMN player_title_id INTEGER NOT NULL DEFAULT 0"); } catch (SQLException ignored) {}
            try { executeSql(stmt, "ALTER TABLE users ADD COLUMN player_title_target_id INTEGER NOT NULL DEFAULT 0"); } catch (SQLException ignored) {}
            try { executeSql(stmt, "ALTER TABLE users ADD COLUMN pay_jewel INTEGER NOT NULL DEFAULT 0"); } catch (SQLException ignored) {}

            try { executeSql(stmt, "ALTER TABLE users ADD COLUMN option_bgm INTEGER NOT NULL DEFAULT 10"); } catch (SQLException ignored) {}
            try { executeSql(stmt, "ALTER TABLE users ADD COLUMN option_se INTEGER NOT NULL DEFAULT 10"); } catch (SQLException ignored) {}
            try { executeSql(stmt, "ALTER TABLE users ADD COLUMN option_voice INTEGER NOT NULL DEFAULT 10"); } catch (SQLException ignored) {}
            try { executeSql(stmt, "ALTER TABLE users ADD COLUMN option_protect_card_r6 INTEGER NOT NULL DEFAULT 1"); } catch (SQLException ignored) {}
            try { executeSql(stmt, "ALTER TABLE users ADD COLUMN option_protect_card_r5 INTEGER NOT NULL DEFAULT 1"); } catch (SQLException ignored) {}
            try { executeSql(stmt, "ALTER TABLE users ADD COLUMN option_protect_card_first INTEGER NOT NULL DEFAULT 1"); } catch (SQLException ignored) {}

            // Migration to fix existing cards with exp=0 which crashes the client
            try { executeSql(stmt, "UPDATE user_cards SET exp = 1 WHERE exp = 0"); } catch (SQLException ignored) {}

            executeSql(stmt, "CREATE TABLE IF NOT EXISTS user_home_backgrounds (user_id INTEGER NOT NULL REFERENCES users(user_id), bg_id INTEGER NOT NULL, PRIMARY KEY (user_id, bg_id))");
            executeSql(stmt, "CREATE TABLE IF NOT EXISTS user_clothes (user_id INTEGER NOT NULL REFERENCES users(user_id), clothes_id INTEGER NOT NULL, PRIMARY KEY (user_id, clothes_id))");
            executeSql(stmt, "CREATE TABLE IF NOT EXISTS user_functutorials (user_id INTEGER NOT NULL REFERENCES users(user_id), tutorial_id INTEGER NOT NULL, PRIMARY KEY (user_id, tutorial_id))");

            log.info("Database schema created/verified");
        } catch (SQLException e) {
            throw new RuntimeException("Schema creation failed", e);
        }
    }

    // ── Users ────────────────────────────────────────────────────────────────
    private static final String SQL_CREATE_USERS = """
        CREATE TABLE IF NOT EXISTS users (
            user_id                  INTEGER PRIMARY KEY AUTOINCREMENT,
            platform_type            VARCHAR(255) NOT NULL DEFAULT 'guest',
            platform_id              VARCHAR(255) UNIQUE,
            device_id                VARCHAR(255),
            nickname                 VARCHAR(255) NOT NULL DEFAULT 'プレイヤー',
            rank                     INTEGER NOT NULL DEFAULT 1,
            exp                      INTEGER NOT NULL DEFAULT 0,
            jewel                    INTEGER NOT NULL DEFAULT 3000,
            pay_jewel                INTEGER NOT NULL DEFAULT 0,
            coin                     INTEGER NOT NULL DEFAULT 0,
            tutorial_step            INTEGER NOT NULL DEFAULT 0,
            profile_background_id    INTEGER NOT NULL DEFAULT 0,
            home_background_id       INTEGER NOT NULL DEFAULT 10001,
            player_title_id          INTEGER NOT NULL DEFAULT 0,
            player_title_target_id   INTEGER NOT NULL DEFAULT 0,
            daily_reward_received_at INTEGER NOT NULL DEFAULT 0,
            comment                  TEXT    NOT NULL DEFAULT 'よろしくお願いします',
            option_bgm               INTEGER NOT NULL DEFAULT 10,
            option_se                INTEGER NOT NULL DEFAULT 10,
            option_voice             INTEGER NOT NULL DEFAULT 10,
            option_protect_card_r6   INTEGER NOT NULL DEFAULT 1,
            option_protect_card_r5   INTEGER NOT NULL DEFAULT 1,
            option_protect_card_first INTEGER NOT NULL DEFAULT 1,
            last_login_at            INTEGER,
            created_at               INTEGER NOT NULL DEFAULT (strftime('%s','now')),
            updated_at               INTEGER NOT NULL DEFAULT (strftime('%s','now'))
        )
        """;

    // ── Items (consumables, materials) ───────────────────────────────────────
    private static final String SQL_CREATE_USER_ITEMS = """
        CREATE TABLE IF NOT EXISTS user_items (
            id         INTEGER PRIMARY KEY AUTOINCREMENT,
            user_id    INTEGER NOT NULL REFERENCES users(user_id),
            item_id    INTEGER NOT NULL,
            quantity   INTEGER NOT NULL DEFAULT 0,
            updated_at INTEGER NOT NULL DEFAULT (strftime('%s','now')),
            UNIQUE(user_id, item_id)
        )
        """;

    // ── Cards (gacha pulls / characters) ─────────────────────────────────────
    private static final String SQL_CREATE_USER_CARDS = """
        CREATE TABLE IF NOT EXISTS user_cards (
            id           INTEGER PRIMARY KEY AUTOINCREMENT,
            user_id      INTEGER NOT NULL REFERENCES users(user_id),
            card_id      INTEGER NOT NULL,
            level        INTEGER NOT NULL DEFAULT 1,
            exp          INTEGER NOT NULL DEFAULT 0,
            awaken_level INTEGER NOT NULL DEFAULT 0,
            skill_level  INTEGER NOT NULL DEFAULT 1,
            is_new       INTEGER NOT NULL DEFAULT 1,
            obtained_at  INTEGER NOT NULL DEFAULT (strftime('%s','now')),
            UNIQUE(user_id, card_id)
        )
        """;

    // ── Chapters (Story/Campaign progress) ─────────────────────────────────────
    private static final String SQL_CREATE_USER_CHAPTERS = """
        CREATE TABLE IF NOT EXISTS user_chapters (
            user_id INTEGER NOT NULL REFERENCES users(user_id),
            chapter_id INTEGER NOT NULL,
            status INTEGER NOT NULL DEFAULT 1,
            PRIMARY KEY (user_id, chapter_id)
        )
        """;

    private static final String SQL_CREATE_USER_CHAPTER_EXPIRES = """
        CREATE TABLE IF NOT EXISTS user_chapter_expires (
            user_id INTEGER NOT NULL REFERENCES users(user_id),
            chapter_group_id INTEGER NOT NULL,
            expires_at INTEGER NOT NULL,
            PRIMARY KEY (user_id, chapter_group_id)
        )
        """;

    // ── Units (Decks/Lineups) ──────────────────────────────────────────────────
    private static final String SQL_CREATE_USER_UNITS = """
        CREATE TABLE IF NOT EXISTS user_units (
            user_id    INTEGER NOT NULL REFERENCES users(user_id),
            idx        INTEGER NOT NULL,
            unit_name  TEXT,
            member1    INTEGER NOT NULL,
            member2    INTEGER NOT NULL,
            member3    INTEGER NOT NULL,
            member4    INTEGER NOT NULL,
            member5    INTEGER NOT NULL,
            card1      INTEGER NOT NULL,
            card2      INTEGER NOT NULL,
            card3      INTEGER NOT NULL,
            card4      INTEGER NOT NULL,
            card5      INTEGER NOT NULL,
            PRIMARY KEY (user_id, idx)
        )
        """;

    // ── Members (Affection levels) ─────────────────────────────────────────────
    private static final String SQL_CREATE_USER_MEMBERS = """
        CREATE TABLE IF NOT EXISTS user_members (
            user_id    INTEGER NOT NULL REFERENCES users(user_id),
            member_id  INTEGER NOT NULL,
            dear_level INTEGER NOT NULL DEFAULT 1,
            likability INTEGER NOT NULL DEFAULT 1,
            PRIMARY KEY (user_id, member_id)
        )
        """;

    // ── Stage clear progress ──────────────────────────────────────────────────
    private static final String SQL_CREATE_USER_STAGES = """
        CREATE TABLE IF NOT EXISTS user_stages (
            id         INTEGER PRIMARY KEY AUTOINCREMENT,
            user_id    INTEGER NOT NULL REFERENCES users(user_id),
            stage_id   INTEGER NOT NULL,
            stars      INTEGER NOT NULL DEFAULT 0,
            best_score INTEGER NOT NULL DEFAULT 0,
            clear_count INTEGER NOT NULL DEFAULT 0,
            cleared_at INTEGER,
            UNIQUE(user_id, stage_id)
        )
        """;

    // ── Story read progress ───────────────────────────────────────────────────
    private static final String SQL_CREATE_USER_STORIES = """
        CREATE TABLE IF NOT EXISTS user_stories (
            id         INTEGER PRIMARY KEY AUTOINCREMENT,
            user_id    INTEGER NOT NULL REFERENCES users(user_id),
            story_id   INTEGER NOT NULL,
            is_read    INTEGER NOT NULL DEFAULT 0,
            read_at    INTEGER,
            UNIQUE(user_id, story_id)
        )
        """;

    // ── Stamina ───────────────────────────────────────────────────────────────
    private static final String SQL_CREATE_USER_STAMINA = """
        CREATE TABLE IF NOT EXISTS user_stamina (
            user_id          INTEGER PRIMARY KEY REFERENCES users(user_id),
            current_stamina  INTEGER NOT NULL DEFAULT 60,
            max_stamina      INTEGER NOT NULL DEFAULT 60,
            last_recover_at  INTEGER NOT NULL DEFAULT (strftime('%s','now'))
        )
        """;

    // ── Gacha log ─────────────────────────────────────────────────────────────
    private static final String SQL_CREATE_GACHA_LOG = """
        CREATE TABLE IF NOT EXISTS gacha_log (
            id         INTEGER PRIMARY KEY AUTOINCREMENT,
            user_id    INTEGER NOT NULL REFERENCES users(user_id),
            gacha_id   INTEGER NOT NULL,
            card_id    INTEGER NOT NULL,
            rarity     INTEGER NOT NULL,
            pulled_at  INTEGER NOT NULL DEFAULT (strftime('%s','now'))
        )
        """;

    // ── Collection (Album) ───────────────────────────────────────────────────
    private static final String SQL_CREATE_USER_COLLECTIONS = """
        CREATE TABLE IF NOT EXISTS user_collections (
            user_id    INTEGER PRIMARY KEY REFERENCES users(user_id),
            bgm_id     INTEGER NOT NULL DEFAULT 1,
            view_count INTEGER NOT NULL DEFAULT 0
        )
        """;

    private static final String SQL_CREATE_USER_COLLECTION_PAGES = """
        CREATE TABLE IF NOT EXISTS user_collection_pages (
            user_id       INTEGER NOT NULL REFERENCES users(user_id),
            idx           INTEGER NOT NULL,
            title         TEXT,
            layout_id     INTEGER NOT NULL DEFAULT 1,
            theme_id      INTEGER NOT NULL DEFAULT 1,
            transition_id INTEGER NOT NULL DEFAULT 1,
            page_sort     INTEGER NOT NULL DEFAULT 0,
            PRIMARY KEY (user_id, idx)
        )
        """;

    private static final String SQL_CREATE_USER_COLLECTION_ELEMENTS = """
        CREATE TABLE IF NOT EXISTS user_collection_elements (
            id            INTEGER PRIMARY KEY AUTOINCREMENT,
            user_id       INTEGER NOT NULL REFERENCES users(user_id),
            page_idx      INTEGER NOT NULL,
            element_index INTEGER NOT NULL,
            element_id    INTEGER NOT NULL,
            element_type  INTEGER NOT NULL,
            UNIQUE(user_id, page_idx, element_index)
        )
        """;

    // ── Presents/Inbox ────────────────────────────────────────────────────────
    private static final String SQL_CREATE_USER_PRESENTS = """
        CREATE TABLE IF NOT EXISTS user_presents (
            present_id      INTEGER PRIMARY KEY AUTOINCREMENT,
            user_id         INTEGER NOT NULL REFERENCES users(user_id),
            category        INTEGER NOT NULL,
            target_id       INTEGER NOT NULL,
            quantity        INTEGER NOT NULL,
            text            TEXT,
            received        INTEGER NOT NULL DEFAULT 0,
            created_at      INTEGER NOT NULL DEFAULT (strftime('%s','now'))
        )
        """;

    // ── Cooking ───────────────────────────────────────────────────────────────
    private static final String SQL_CREATE_USER_COOKING = """
        CREATE TABLE IF NOT EXISTS user_cooking (
            user_id         INTEGER NOT NULL REFERENCES users(user_id),
            tray_id         INTEGER NOT NULL,
            recipe_id       INTEGER NOT NULL,
            start_at        INTEGER NOT NULL,
            finish_at       INTEGER NOT NULL,
            PRIMARY KEY (user_id, tray_id)
        )
        """;

    // ── Home Actors ───────────────────────────────────────────────────────────
    private static final String SQL_CREATE_USER_HOME_ACTORS = """
        CREATE TABLE IF NOT EXISTS user_home_actors (
            user_id       INTEGER NOT NULL,
            character_id  INTEGER NOT NULL,
            model_kind_id INTEGER NOT NULL DEFAULT 1,
            clothes_id    INTEGER NOT NULL DEFAULT 0,
            position      INTEGER NOT NULL,
            PRIMARY KEY (user_id, character_id),
            FOREIGN KEY (user_id) REFERENCES users(user_id) ON DELETE CASCADE
        )
        """;

    // ── Friends ───────────────────────────────────────────────────────────────
    private static final String SQL_CREATE_USER_FRIENDS = """
        CREATE TABLE IF NOT EXISTS user_friends (
            user_id         INTEGER NOT NULL REFERENCES users(user_id),
            friend_id       INTEGER NOT NULL REFERENCES users(user_id),
            status          INTEGER NOT NULL DEFAULT 0,
            created_at      INTEGER NOT NULL DEFAULT (strftime('%s','now')),
            PRIMARY KEY (user_id, friend_id)
        )
        """;

    // ── Blocks ────────────────────────────────────────────────────────────────
    private static final String SQL_CREATE_USER_BLOCKS = """
        CREATE TABLE IF NOT EXISTS user_blocks (
            user_id         INTEGER NOT NULL REFERENCES users(user_id),
            blocked_user_id INTEGER NOT NULL REFERENCES users(user_id),
            created_at      INTEGER NOT NULL DEFAULT (strftime('%s','now')),
            PRIMARY KEY (user_id, blocked_user_id)
        )
        """;

    private static final String SQL_CREATE_USER_GACHA_HISTORY = """
        CREATE TABLE IF NOT EXISTS user_gacha_history (
            user_id         INTEGER NOT NULL REFERENCES users(user_id),
            gacha_id        INTEGER NOT NULL,
            total_cnt       INTEGER NOT NULL DEFAULT 0,
            free_roll_used  INTEGER NOT NULL DEFAULT 0,
            limit_cnt       INTEGER NOT NULL DEFAULT 0,
            pending_choice_cnt INTEGER NOT NULL DEFAULT 0,
            PRIMARY KEY (user_id, gacha_id)
        )
        """;
}
